### ISSUE TITLE
RTE link once created supposed to editing

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#1379]
When link is created from RTE, we shohuld exit editing mode and allow user to change the href for  the link right away

## Todo

When link was created

- [ ]  exit editing mode
- [ ] select new link instnace
- [ ] switch right sidebar to settings panel

**Comment by TrySound** [comment]
We never had this before. It was implemented only for spans

**Comment by kof** [comment]
Updated description

**Comment by kof** [comment]
duplicate of https://github.com/webstudio-is/webstudio/issues/66
