### ISSUE TITLE
ChatGPT Integration

### ISSUE THREAD

**Issue by gsppe** [webstudio-is/webstudio#1450]
→ [Progress information](https://github.com/webstudio-is/webstudio-builder/issues/1450#issuecomment-1523612309) (updated daily).

Integration experiments (PRs that can be cloned and tested locally):
- v1 https://github.com/webstudio-is/webstudio-builder/pull/1527
- v2 (**current**) (YAML -> WS) https://github.com/webstudio-is/webstudio-builder/pull/1608

---

We want to explore a ChatGPT integration in Webstudio. 

The ultimate goal would be to allow users to create pages or sections of them with prompts. On a high level this means getting instructions in natural language and generating structured content that is compatible with Webstudio's serialization format, resulting in the tool producing actual code.

At this stage it is hard to anticipate all the necessary steps to get to the final result therefore consider this issue as WIP and an evolving one or even a request for comments (RFC) - feel free to comment below.

Given that this is a greenfield project for now we'll organize in three phases: 

1. Validation and solution design
2. System design and API implementation 
3. Integration in the builder UI

Each phase will be broken down further in order to go in steps and reduce risk (feasibility/time/resources).

## Phase 1 - Validation

The bulk of the work / complexity of this project is all about prompt engineering. We need to figure out a precise way of crafting prompts so that we provide all the information necessary to generate valid structured content. This is a non-trivial task. 

While initially I will be playing with the free ChatGPT UI, soon I might need an API key:

- [x] @kof to provide an OpenAI API key if necessary

In this phase we want to:

- [x] Explore the current capabilities of ChatGPT (quality of output and the like). 

This is prompting engineering work that will go towards trying to understand if the tool can fulfill requests such as creating a landing page or parts of it and then generate precise answers in a format that we expect (HTML or similar). 

A non-comprehensive list of things to try (please add suggestions):

- [x] Explore current understanding of HTML/CSS and quality of the output 
- [x] Ask GPT to produce an [hast](https://github.com/syntax-tree/hast) (HTML AST) might be an idea worth trying as it might already know about it
- [x] Try the same as above but with React components?
- [x] Using Webstudio's components' signatures/metadata try to craft an example for GPT for the `Box` component - this will go along with the user prompt 
- [x] Explore nesting

Questions:

- [ ] It'd be great if you could provide pointers to Webstudio's specific bits that I might need to know about: i.e. components, metadata, public type definitions and basic architectural information like: how is CSS handled. Of course I can figure all this out myself but probably we'll save a decent amount of time if I get a tl;dr from you.

--- 

- [ ] Research current approaches (if any) to solve similar problems - it is always worth researching existing academia or public work/solutions 

- Builder.io seems to generate React and (I imagine inject whatever they get without following a hyper strict schema) [[link](https://www.builder.io/blog/build-with-ai#generate-visually-editable-components-from-prompts)]
- TeleportHQ seems to generate a [Unist](https://github.com/syntax-tree/unist)-like AST [[link](https://www.youtube.com/watch?v=fq1RPJUI_GM)]

---

- [ ] Work towards defining a structured text format (a schema) from existing Webstudio information to feed to ChatGPT. 

Webstudio's schema is [here](https://github.com/webstudio-is/webstudio-builder/tree/main/packages/project-build/src/schema). 

Since Webstudio is quite young and there were not docs out there GPT doesn't know much about it. Therefore this should educate ChatGPT about the Webstudio's structured content format. 

user request + examples is for **what** we want
the schema definition is for **how** we want it

The [Webstudio schema](https://github.com/webstudio-is/webstudio-builder/tree/main/packages/project-build/src/schema) is normalized, flatten and actually quite complex (full of references) so GPT might struggle generating something that describes a UI in that format.

I am are currently exploring the option of using [Webstudio Embed Templates](https://github.com/webstudio-is/webstudio-builder/blob/main/packages/react-sdk/src/embed-template.ts#L63-L77) instead which are much simpler. [Example templates](https://github.com/webstudio-is/webstudio-builder/blob/main/packages/react-sdk/src/embed-template.test.ts).

---

- [ ] Work towards creating a standard prompt format to provide extra context for components

Likely this will be needed to teach GPT about what **props** components accept.

We need to figure out the minimum amount of information to create a quality emebedding for the component. [Here](https://www.youtube.com/watch?v=Ue7M826xj5M)'s a decent and easy to grasp explanation of what embeddings are.

[Embeddings](https://platform.openai.com/docs/guides/embeddings) measure the relatedness of text strings. The idea here is that:

1. we create an archive of embeddings that describe the whole Webstudio components library and save them on a vector db
4. when a user prompt comes in we generate an embedding for that prompt
5. fetch the top N related Webstudio embeddings from the vector db
6. construct the prompt with user request + examples (top N related embeddings' metadata)

In the beginning as we explore an MVP we'd skip the vector db and store to file. Once validated we should move to a vector db right away.

For this part we should use (and perhaps enrich) the [Webstudio components' metadata](https://github.com/webstudio-is/webstudio-builder/blob/1ecea88ddb1fadd956ff670d850b1690247c94c6/packages/react-sdk/src/components/box.ws.ts#L35) and possibly the [generated types](https://github.com/webstudio-is/webstudio-builder/blob/1ecea88ddb1fadd956ff670d850b1690247c94c6/packages/react-sdk/src/components/__generated__/box.props.ts). 

---

## Phase 2 - System design and API implementation 

**IF Phase 1 is successful/works** then we'll have to make more concrete design decisions about:

- [ ] Implement solution in code based on decisions above - this would be an wip API endpoint that can be used headlessly  - a WIP implementation to test end-to-end can be found in https://github.com/webstudio-is/webstudio-builder/pull/1608
- [ ] a solution that fits the current token limits: I think it is 4k tokens. With GPT4 the limit is 8k to 32k tokens.
- [ ] defining final spec for embeddings generation and structured content
- [ ] generating and storing embeddings upon changes and manually
- [ ] operational things like rate limits, hosting requirements and issues that might arise due to OpenAI's API usage
- [ ] storing accepted GPT answers for future context and to improve prompts. Carefully consider all the privacy implications of this (maybe per-user storage and not shared is the most safe option).
- [ ] product in general

---

## Phase 3 - Execution

- [ ] Integrate the API above in the builder UI/app - a WIP implementation to test end-to-end can be found in https://github.com/webstudio-is/webstudio-builder/pull/1608

**Comment by ggurgone** [comment]
Using this comment to track

# Explorative Prompt Examples

To test the capabilities of ChatGPT I am asking it to replicate some of the layouts from here [https://library.relume.io/components](https://library.relume.io/components). 

It is important to note that I won't provide any code example just a description of the page layout.

## Example 1

Blog overview page.

[Reference Design](https://library.relume.io/components/blog-3)
[GTP Result](https://jsfiddle.net/xonymp3w/)

<details><summary>Prompt</summary>

You are NoCodeGPT a no-code tool for designers that exclusively generates clean HTML code from user prompts. CSS is exclusively written inline using the style attribute, no <style> tags. Don't use any framework or external library. Return HTML only, I only want code and no free form text messages from you!

Can you create a page with a centered logo at the top. Right below there is the page title in bold, it is big. Below the title there is an horizontal navigation with 3 links: Home, About and Contact. Each link looks like a simple button with a stroke border, no round corners.

Finally below there is a grid of boxes, 3 per row. Each box looks like a card, with an image on top and below showing the Category, Post Title, Excerpt and author avatar. All the content is vertical.
</details> 

Overall Quality: Good

**Comment by ggurgone** [comment]
## Progress

Integration #1527 

### 26 April:

- Reworked the UI integration to split generation into steps (instances, styles generation etc) and multiple requests.
- I spent a bit of time (but had not luck) trying to optimize GPT output for styles which quite often is too long. This means we hit the 2k tokens limit and therefore parsing the response fails. I will bump the token limits to the max and we'll look into ways to optimize this later.
- Started to look into how applying the template so we can see the result visually

### 24-25 April:

- Started UI integration to enable end-to-end iteration, experimentation and testing. see #1527 
- Discussed about ui integration and plugins.

Experiments #1478 

### 20 April:

I started to explore the option to break the generation process in steps:

1. Give initial context to generate `instances`
2. Use generated `instances` to generate `breakpoints`, `styles`, `styleSourceSelections` and `styleSources`
3. todo next: use generated `instances` to generate `props`

The main problem that I have encountered is that it often gets instances generation wrong by nesting `children` instances instead of producing a flat and normalized array of instances. 

Take a look at example 15:
- [prompt](https://github.com/webstudio-is/webstudio-builder/pull/1478/files#diff-73719401d159bdff8ee8b173c89c037263fed1557239efbcb73857a0dd520847)
- [result](https://github.com/webstudio-is/webstudio-builder/pull/1478/files#diff-db5bc06af28d40338499c2f14f6a16a9434ed209d3e7ed99628a1ea6aaaa3154)

**ANY** prompt idea that can help fix this is welcome. I even gave it an example of an invalid output but it ignores it often times.

Another small problem might be the speed at which it generates responses. It might take a few tens of seconds to get a full answer.

To test locally:

- checkout this branch (`gpt-experiment`)
- `pnpm install && cd packages/gpt`
- create an `.env.local` file: `cp .env.example .env.local`
- set OpenAI API key and OpenAI org id (you can find it at [https://platform.openai.com/account/org-settings](https://platform.openai.com/account/org-settings))
- create a prompt file inside of the `tests` folder: copy `15-blablab.md` to `16-your-test-name.md`
- run `pnpm ask 16-your-test-name.md 16-your-test-name.out.md` 

### 19 April:

Explored more refined prompts and tried to add context for breakpoints, styles, styleSourceSelections and styleSources. The results are somewhat ok but not flawless. 

I also wrote a small script so that I can use the API from the command line and set the `temperature` to `0` (forcing GPT to strictly follow the rules and avoid it getting too creative).

### 18 April:

By the end of the day here's where I am at https://github.com/webstudio-is/webstudio-builder/pull/1478/files#diff-ca76c023a7bb5ecac41fa1ca6de066e4075e5d5d577f2a25ff70eb7570f85c26

Looks encouraging but often the result in not 100% accurate in terms of structure, especially when it comes to instances and nesting. I have the feeling that this can be improved with [fine-tuning](https://platform.openai.com/docs/guides/fine-tuning) when we will have a final shape of the schema and can generate examples. 

Fine-tuning can also help reducing the costs because we won't need to provide examples or info about the schema with every prompt, since the fine tuned model already has these information.

Anyway, tomorrow I will continue on the path I have taken today. Trying to normalize the styles types because they are huge and don't fit in a prompt.


### 17 April:

- Some setup work
- Created a script to convert zod types to TypeScript.
- Edited types to comply with Webstudio's serialization format - eg. from `Map<string, Instance>` to `[Id, Instance<Id>][]`
- Crafted first prompt: See tests/1.md and tests/1.out.md

It is clear from the beginning that we need to be super greedy with our context length and optimize like crazy otherwise we will hit the tokens limits.

- We need to improve the TypeScript [schema](https://github.com/webstudio-is/webstudio-builder/tree/main/packages/project-build/src/schema) generation script (zod to TS)
- We need to normalize everything, especially the schema definition for props and styles. I'd say we should aim for a budget of 1000-1500k of tokens for this (very hard task).
- Do more testing
