### ISSUE TITLE
New CLI

### ISSUE THREAD

**Issue by andrasbacsai** [webstudio-is/webstudio#1825]
CLI should be able to easily generate assets (HTML, JS, CSS, images, etc.) from any (hosted or self-hosted) webstudio instances so that people can deploy them anywhere.

It will be used in the workers deployment.

## Todo
- [x] Authenticate with pre-generated shared links.
- [x] Download the site data.
- [x] Build site from site data.
- [x] license for the cli
- [x] disable warnings
- [x] build folder is missing in published package
- [x] favicon missing from the build. Need to setup a default one
- [x] link command should not wait for the prompt if it is passed as argument . Instead can take from the command itself as a argument
- [x] publish to vercel breaks with a jsep dependency issue.
- [x] run init when running `webstudio` without a command, init is a setup assistant
   - [x]  if there is no config yet, on init ask user if they want to create a folder and prompt one otherwise go with ./
   - [x] if there is no config yet, ask for url if there is no config
   - [x] runs the sync
   - [x]  runs the build
   - [x] starts the server, prints the local url
   - [x] shortcut to open in the browser (like in partykit and wrangler)
- [x] all commands should be available without running init
- [x] test deployment to vercel
- [x] use vercel's image optimizer
- [x] implement the dialog  https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=7145-55747&mode=design&t=lO3H4FkCJZYzD4Gr-0
- [x] add "Export" to the horizontal menu
- [x] update readme
- [ ] use CLI to publish to workers for webstudio
- [x] use CLI to publish on builder preview to vercel 
- [x] check where url should be stored since its a secure link that includes password, add a way to provide it from env for CIs
- [x] add link to readme to the cli output
   
From @istarkov 

- [x] We must have a way to test cli immediately i.e be able to run it through tsx at least to be able to change parsing logic etc without recompiling.
- [x] Now no way to add args to build command only or to any other command like its done in most modern cli parsers.
- [x] build:templates not documented at all, Im not getting why and what it's doing. Generated files are not human readable.
- [x] This is how route-template.tsx looks like in vscode, errors erros errors. If it template it should not have tsx extension
- [x] build:templates from what I see just move files into string variables, files and folders are readable
this https://github.com/webstudio-is/webstudio-builder/blob/37dd70154603eb04c2b1486c894fff5c958504b1/packages/cli/src/__generated__/templates.ts#L12 is not
How to test, I need to be able to run it in our env for example on predefined project and see the generated result. See changes in git if something has changed

**Comment by JayaKrishnaNamburu** [comment]
Adding a todo, with testing on some big projects and some stuff. I noticed that
- [ ] Nested routes behaviour is buggy and little in-consistent. It needs to be fixed

**Comment by JayaKrishnaNamburu** [comment]
Linking all the PR's that implements the behaviour

#2018 - for linking projects in local
#2033 - to sync the deployed project to local
#2035 - build the synced project, basically scaffolding, creating routes, bundling with the template
#2133 - download assets to local and serve from `public` folder.
