### ISSUE TITLE
Small UX improvements based on user feedback

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#2324]
- [x] Stop scaling instance labels https://github.com/webstudio-is/webstudio/issues/1990
- [x] Add a shortcuts help panel -  https://github.com/webstudio-is/webstudio/issues/2354
- [x] Open settings panel when adding Image, Link and others probably needs meta option, alternatiev open quick settings popover https://github.com/webstudio-is/webstudio/issues/2355
- [x] When opening preview mode - open full width
- [x] Preview blend mode values on mouse hover (all selects, including display)
- [x] Fonts picker item mouse cursor is text, should be normal
