### ISSUE TITLE
Quick settings popover

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#2355]
When adding a component to the canvas, some components need a quick settings popover. Reason is that user will want to change those right away. Examples: image (user will want to set src), link (user will want to set href)

## Todo

- [ ] make a design proposal
- [ ] add a property to meta that will enable showing the popover upon component creation
- [ ] render all initial properties in popover

**Comment by taylornowotny** [comment]
Two initial questions.

1. Do we want to show all properties, or just specific ones for specific components? Are we showing anything other than Properties from the Properties section of the Settings panel?

2. Do we want this to be part of the context menu or separate?

Webflow separates them. Right click an element and you get a context menu:
<img width="245" alt="Screenshot 2023-09-25 at 12 35 21 PM" src="https://github.com/webstudio-is/webstudio/assets/86495896/3a9415f2-86aa-4389-8c50-b1e15aa6d69e">

Some (not all) elements have a gear icon that you can click to show limited quick settings:
<img width="305" alt="Screenshot 2023-09-25 at 12 38 37 PM" src="https://github.com/webstudio-is/webstudio/assets/86495896/48abaa68-819b-4949-862f-31694d6e401b">

**Comment by kof** [comment]
I think we should separate those things, context menu will have enough to deal with.

> Do we want to show all properties, or just specific ones for specific components?

All initial properties for the specific component seems like an obvious choice to me

**Comment by taylornowotny** [comment]
Agreed, I will follow up with a design proposal soon
