### ISSUE TITLE
AI Generation

### ISSUE THREAD

**Issue by gsppe** [webstudio-is/webstudio#2375]
We want to create a feature to generate sections or pages with AI. The user should be able to insert a prompt and get generated UI.

The process for v1 will be the following:

* AI chain breaks down user prompt into a list of sections with title and description
* For each section we call an AI chain to generate JSX using all the Webstudio component names. For styling we use Tailwind CSS converted to `local` styles
* Transform JSX to Webstudio Embed Template
* Insert template on page

- [x] #2378 Implements chains and business logic above
- [x] #2379 Implement prototype UI
- [x] Implement template insertion
- [x] Implement final UI once design is ready 
- [x] testing

#### Dependencies

- [x] @taylornowotny to decide on final UI/UX (#2371)
- [x] @istarkov implements Tailwind CSS to Webstudio converter
- [x] AI endpoints rate limiting

#### Potential future features

- [ ] Tailwind CSS is converted to Webstudio Design Tokens instead of `local` styles
- [ ] Add editing functionality thanks to the above
