### ISSUE TITLE
Bindings UI

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#2532]
As a user I want to be able to bind any property value or any style value to a variable.

https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=6762-5213&mode=design&t=7YK2gNrt153ZR796-0

![image](https://github.com/webstudio-is/webstudio/assets/52824/25754abf-3e3a-426b-b465-3b7c7773e514)

## Fundamental UX

- [x] 1. A user can change any value, style or props at any point of time, even if the value is bound to a variable
- [ ] 2. We should do the same thing as point 1 for value bound to expression (next iteration)
- [x] 3. We want to indicate the bound state using a light blue color (same as style panel property label)
- [x] 4. We show the dot permanently when the value is bound (smaller dot for permanent state)
- [x] 5. Text content should be editable just like in point 1 

## Todo for data sources and bindings launch

- [x] Add variables section to settings which has + and delete button and shows ONLY instance variables
- [x] Click on + for adding variable opens a floating panel
- [x] make sure the first focused item when opening any popover/floating panels is selected wisely, e.g. new variable popover should have Name focused initially
- [x] Remove +, delete button and editing variable  from floating panel for bindings (rename the panel  from "Variables" to "Binding")
- [x] We use the "dot" UI as a button to show binding UI. 
- [x] We show all dots using a keyboard shortcut. We hide all of them using the same shortcut.
- [x] when binding has not yet been added, we should probably disable "delete" button, otherwise its not clear what you might be deleting since there is not value set
   <img width="251" alt="image" src="https://github.com/webstudio-is/webstudio/assets/52824/bb4cbe25-2a1f-46f2-96e3-f2824f293e9d">
- [x] can't close the binding dialog when I deleted expression value, seems like a natural way would be when user deleted expression and is closing the dialog to act same way as with clicking delete button
    <img width="504" alt="image" src="https://github.com/webstudio-is/webstudio/assets/52824/2d0fc6e4-4305-4d8d-9416-204e1f11d602">
- [x] position of the binding dialog is a little strange, we need to think of something better
    <img width="304" alt="image" src="https://github.com/webstudio-is/webstudio/assets/52824/2de7e21c-6448-44d3-9bdd-3eb7a596c17e">
- [x] lets get rid of cancel/save buttons

    I think we can do the following: 
    1. while user is typing we don't show errors right away
    2. when input gets unfocused - we validate and show error
    3. when user starts typing while having error state, we remove the error and go from point 1
    4. we also indicate the error with a red border (I afaik ds input has state error like that and code input should too)
    5. if input is in error state and user closes - don't save the error state, show error if user just made changes, but if user closes again, discard changes

   <img width="253" alt="image" src="https://github.com/webstudio-is/webstudio/assets/52824/d56b3d49-66a0-438c-add7-3819ff9e0947">

   <img width="253" alt="image" src="https://github.com/webstudio-is/webstudio/assets/52824/a94eedb3-91fb-4fd3-9c52-d1692a9ca67a">
- [x] seems like you are not using floating panel, it should position on the left from the settings panel, like with all other panels e.g. box shadow, fonts, transitions etc

    <img width="323" alt="image" src="https://github.com/webstudio-is/webstudio/assets/52824/d140df59-57a6-4fc2-ad9d-69ca4dca8649">

- [x] when value is bound to an expression, the input looks weird with the background color inside, probably it comes from the editor, what can we do about it? I know its not part of this PR

    <img width="241" alt="image" src="https://github.com/webstudio-is/webstudio/assets/52824/aca69ef5-07ad-4821-93c3-7c47506fdbf3">
- [x] I managed to bind tag property and render box as an anchor by using value "a" , this should be impossible, since in this case only values provided by the select box should be possible (I know its not part of this PR)

   <img width="241" alt="image" src="https://github.com/webstudio-is/webstudio/assets/52824/369de330-d54b-46ca-bec8-ed124e243fce">
 
- [x] Just noticed that this is not using floating panel component

    <img width="493" alt="image" src="https://github.com/webstudio-is/webstudio/assets/52824/c08a8d39-980d-4525-9175-befbb5a353cc">
    
- [x] noticed that user can have right now both Value and Ressource, but only one can be possible at the same time, so there is a UI issue, we are not telling the user this, we need to figure out the best possible UI for this, it might be that tabs is not a fit at all    

- [x] use data type select instead of tabs, add String,  Number, JSON, Ressource   

- [x] buttons gap too small (Binding panel)

<img width="78" alt="image" src="https://github.com/webstudio-is/webstudio/assets/52824/f43140ab-6733-4847-b5cc-d349b9eca74b">

- [ ] add subtitles and tooltips in Binding popover

<img width="504" alt="image" src="https://github.com/webstudio-is/webstudio/assets/52824/a2759e5d-abc6-40bb-8a75-af74cb8b3403">

## Enhancements & bugs

- [x] variables like collectionItem should be "Collection Item" in the UI and "collectionItem" in generated code
- [x] remove drag handle
- [ ] don't update canvas if variable or expression is invalid
- [x] selecting item from variable autocomplete with mouse doesn't work
- [ ] ~~we move the binding dot to the right side~~
- [ ] we make the dot visually slightly smaller while the surface area stays the same

## Todo for the general variables launch

- [ ] #2750
- [ ] ~~Add binding UI shortcut to the global dropdown menu~~
- [ ] Add a global variables manager accessible from the left sidebar icon button and a shortcut, only for global variables
- [ ] Add CSS data type
- [ ] In datatype CSS user gets a combobox to select property or type a custom property (--something) and gets a css value input
- [ ] Able to bind any style panel value
- [ ] make codemirror tab/esc behavior accessible, right now it prevents popover from catching the esc event even if there is no autocomplete open
- [ ] ellipsis shown after the entire variable name that includes type, maybe we should allow the type to be always visible (its a minor thing) 
    <img width="247" alt="image" src="https://github.com/webstudio-is/webstudio/assets/52824/07585c04-cea3-4452-ba51-871edd587a40">

**Comment by kof** [comment]
Here is an interesting pattern Webflow uses to handle deletion of a bound variable, it lets you delete the variable no questions asked, but in places where its still being used you see this and you can restore the variable or unlink. They don't truly delete a variable if its still being used:

<img width="253" alt="image" src="https://github.com/webstudio-is/webstudio/assets/52824/0a7013ba-6791-4e65-bef6-1768fd0c01ed">

<img width="463" alt="image" src="https://github.com/webstudio-is/webstudio/assets/52824/2b3b4bd8-121e-4242-801e-526104e9b502">
