### ISSUE TITLE
Unify code editing experience in style panel for complex values

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#2967]
- [x] Put code editor at the bottom of background gradient panel (to be consistent with box shadow, transitions) #3445 
- [x] Add code editor to background image #3445  
- [ ] ~~Use the new code editor component everywhere: backgrounds, transitions, box shadows, filter~~
- [x] When there is only one layer, drag handle shouldn't be visible, this is for all layered properties #3445
- [x] Save text values when closing/blur content box.
- [x] updating values on scrub instead of using ephemeral flag, which makes it slow https://github.com/webstudio-is/webstudio/pull/3318#pullrequestreview-2046045009

**Comment by TrySound** [comment]
Let's not use autocompletion here at all, there is not much to suggest here

**Comment by JayaKrishnaNamburu** [comment]
> Let's not use autocompletion here at all, there is not much to suggest here

I second this, because we are ading the UI controls to manage the same anyways. I will handle the rest and move to transforms.

**Comment by kof** [comment]
Yes, lets not have autocompletion there
