### ISSUE TITLE
Improve autoplacement logic for components

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3149]
When user inserts components 
- with 1 click from components panel
- by pasting
- later by using shortcuts

We need a simple logic to decide whether component should go inside or after the selected instance.
The decision is to go for this logic:

>  if instance has at least one text node - we don't insert inside. This way we avoid inserting inside Headings, Text etc

Root is the only exception - always insert inside at the end.

### Part 1
- [x] move placeholders to meta templates
- [x] add placeholder: boolean flag to text nodes {type: text, value: string, placeholder:true }
- [x] use the new flag in  AI package to skip placeholder https://github.com/webstudio-is/webstudio/pull/2399
- [x] can delete this logic $convertTextToLexical and not run into https://github.com/webstudio-is/webstudio/issues/2732

### Part 2

- [ ] implement the new logic
