### ISSUE TITLE
Linked CSS editor

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#34]
We should show a CSS block representing the style of the selected element as an editable CSS text, because

1. It lets a user with CSS skills see what is actually defined in a text form, which is potentially much shorter than UI
2. User can edit that CSS as text, when they know what they need to change
3. User can copy/paste that - enables also cloning styles across projects
4. User can **learn** CSS by looking at the CSS text generated by the UI and vice-versa

We should provide user with all possible autocomplete UIs:
- property name autcomplete
- CSS keywords autocomplete
- unit autocomplete

## Todo

- [ ] Render the CSS rule style block preview as a CSS section (no selectors/media queries, just the block)
- [ ] When editing, reflect the changes in the UI
- [ ] When editing, update on the canvas
- [ ] Changes from style panel should automatically reflect in the editor

**Comment by smotched** [comment]
This is an awesome idea!

**Comment by kof** [comment]
I think we could create a first version without any autocompletes, a very simpleone, but it would already work for copy/pasting CSS from/to Figma which is a huge win and it would be in sync with the style panel.

wdyt @okonet @thysultan
