### ISSUE TITLE
Improve page settings for marketplace

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3405]
## Stage 1

- [x] Lets make the activation for the marketplace the first checkbox you need to activate before all other settings in project settings/marketplace are visible, because this will allow us to show the new settings in the page settings more obvious, otherwise you would have to publish to marketplace first and only then see the page settings for marketplace.
- [x] Render marketplace card in the new Marketplace Settings section
- [x] use page name as a title for the marketplace card
- [x] add a separate thumb image for the marketplace, fall back to social preview image from assets
- [x] use a category input for category
- [x] if ws:title or ws:category is defined fall back to it

## Stage 2
- [x] migrate ws:title and ws:category
- [x] delete ws:title and ws:category hint from marketplace settings
