### ISSUE TITLE
Lets make loading of the builder delightful

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3520]
Current state:
https://share.descript.com/view/vUVelI75aPC

1. click on thumbnail - loading indicator is good
2. 0:09 first initial screen rendering - good, no junk, but also no loading status, despite still loading all the data
3. 0:24 breakpoints and right panel tabs appear - completely unnecessary, since the rest is still not working
4. 0:28 body instance gets selected, style panel shifts, unnecessary
5. 0:29 final render

## Todo

- [x] step 3 and 4 don't exist
- [x] show loading on top of builder like figma does
- [x] optionally also animate canvas (might not work well)  
- [x] remove outlines when going away from project to dashboard, otherwise when coming back outlines are still hanging
- [x] hide resize canvas handle
