### ISSUE TITLE
Installable marketplace projects

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3535]
As a designer, I want to be able to have a quick access any project from a marketplace, e.g. to a section templates library project.

Right now, inserting any specific template is this:

1. click 1 open marketplace
2. click 2 optionally open second tab
3. click 3 open the project
4. click 4 insert the right page/section template

WIth an ability to add project to your sidebar, it will become:

1. click 1 in the sidebar to open project
2. click 2 to insert the right page/section tempalte

This is mostly useful for section libraries and will be very handy for all the opinionated components e.g. section.

## Todo
- [ ] install button for each marketplace project
- [ ] make sure project has a favicon
- [ ] add a new section to the left sidebar, with some visual separation from the rest
- [ ] on click open directly the project view just like in marketplace
