### ISSUE TITLE
Install any project using a shared link

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3536]
Next stage after https://github.com/webstudio-is/webstudio/issues/3535 is to be able to install any project you have a shared link to, even if its not in the marketplace

This would allow you to install a project privately, without needing to go over the marketplace.

## Todo

- [ ] Add button on the sidebar, maybe context menu to avoid clutter
- [ ] Input popover or dialog to paste a shared link
- [ ] Once shared link is pasted the rest should go same as in https://github.com/webstudio-is/webstudio/issues/3535
