### ISSUE TITLE
Allow publishing from builder directly to any other platform

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3654]
As a developer, I want to set up publishing to Vercel or Netlify using the CLI in a way that allows designers on the team to publish directly to those platforms from the builder, without needing a developer to use the CLI.

## Todo
- [ ] add Publishing setting to project settings
- [ ] allow entering webhook url with a key https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event
- [ ] use the provided key to publish instead of our default publish pipeline
