### ISSUE TITLE
Better UI for working with APIs

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3691]
As a builder, when creating a complex query for a Resource, I have several issues:

1. the need to define a number of query params and doing it all conditionally in one url string template is too hard and unreadable
1. need to switch between data inspector and variable/resource UI 
1. need to know the dot notation syntax to access nested properties
1. need to know the expressions syntax, even though its just javascript, a way to not know it would be great
1. convert a string, e.g. "en_US" to "en" currently requires a backend, where it could be just an expression or a function that runs directly in webstudio

## Todo

- [x] Better UI to define query string
- [x] Better way to see data instead of switching to inspect window
- [x] store json expression in search params and headers
- [x] manual cache control
- [x] explicit body type
- [x] show inspect when create new variable
- [ ] update templates to use separate fields
- [ ] autocompletion for standard header names
- [ ] Expression for selecting data, the "data.x.y" notation would be inserted by clicking on data nodes automatically, so one doesn't need to type or know that object syntax
- [ ] url pattern syntax with auto generated fields like in framer
- [ ] Ideally expressions would also have an interface to build them without knowing syntax or alternative is AI generation in-place
- [x] Missing methods in expressions is bad too, because you often want to do little manipulations, a js function instead of expression would allow to write js and would be much more powerful and easier for devs

**Comment by MilanBgd** [comment]
Make.com has a following UX on the HTTP module. You can add different parameters on query strings. Maybe this UX can help you to be inspired for the feature.

<img width="994" alt="SCR-20240729-mybp" src="https://github.com/user-attachments/assets/d1652367-84e2-4ad9-a82f-52acac28632d">

**Comment by kof** [comment]
@MilanBgd that's the same thing we already have for headers, but yes, we need this

**Comment by johnsicili** [comment]
I know this issue is about query params, but I'll throw in this somewhat adjacent use case: Many query param _values_ can get complex too. 

Here is a Baserow query param:

<img width="813" alt="baserow" src="https://github.com/user-attachments/assets/e6623b0f-6417-4259-a49e-59a8bf42f115">

Luckily line breaks appear to work making organization easier. Some APIs don't like the line breaks. So maybe at minimum just add something to remove line breaks or something to manage and stringify an object 🤷

**Comment by kof** [comment]
Would love to see any UI that allows to nicely define that query

**Comment by kof** [comment]
Framer automatically adds input fields when url contains params like /:param - we should copy that

https://github.com/user-attachments/assets/94833086-a97a-478d-b481-7894b74a197f

**Comment by kof** [comment]
Additionally we need a way to copy the resource into the buffer when trying to copy a resource from one project to another and keep the URL stirng with params as params and values as separate fields. 

This way we preserve the exact same presentation  and keep complex URLs readable

**Comment by TrySound** [comment]
This is actually how we implemented "Address bar" for dynamic pages.

**Comment by kof** [comment]
> This is actually how we implemented "Address bar" for dynamic pages.

Very close, yeah.

**Comment by TrySound** [comment]
Proposal for future

<img width="1972" height="1228" alt="Image" src="https://github.com/user-attachments/assets/8e23ff53-195d-4c00-991b-cfd382092779" />
