### ISSUE TITLE
Content Mode

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3994]
As a builder, I want to let a customer edit text and images without giving them the full power of the builder.

Here is how it can work:

## Step 1. Add Content Edit mode to the panel (similar to Preview button at the top panel).
- [x] Remove Style panel
- [x] At left show Pages, Navigator, Assets 
- [x] Disable Binding editing.
- [x] Disable Canvas drag.
- [x] Disable Tree drag.
- [x] In the properties panel, show only Link and Img tag default properties (but not ID or Class), do not allow add new properties. 
- [x] Do not show/allow bindings editing (text editing in binded instances too).
- [x] Disable copy/paste
- [x] Add EditContent button
- [x] Enable text editing functionality.
- [x] Probably allow text editing in a single click instead of double click in Edit Mode.
- [x] Make edit styles (i.e. show "text" cursor on editable text)

 Roll out without feature flag or public announcement.

## Step 2. Add "content editor" Share link.
- [x] Do some system rest API checks to not allow patching styles, props (only img and link are allowed)
- [x] Free users can't share Content Edit Link
- [x] All shared links from Free users must not have Content Edit mode

Roll out without feature flag or public announcement.

## Step 2.5 Add combo for modes
- [x] - Switch preview, design, content using combo like switch
- [x] - Padding right at menu is not ok (#4484)
- [x] - Order Design/Build/Preview (#4484)
- [ ] - Rename modes (Visible Text initially)
- [x] - Do not reset to preview automatically (#4484)
- [x] - Button zone (#4487)
 
## Step 3. Allow content Editors to upload and modify images

- [x]  Roll out without feature flag or public announcement.

## Step 4. Introduce the `EditableBlock` component.

```
EditableBlock
   - Templates (Designers can add components within a controlled template area.)
     - Header
     - Article 
     - Anything 
  - Header Edited By user
  - Article Edited By user   
  - Article Edited By user   
```   

- [x]  The content editor can copy components from the `Templates` area directly into the `EditableBlock`, making them immediate children of the `EditableBlock` _(UI inspired by Notion or potentially with a “+” button at the bottom of each block, open for discussion)_.

- [x]  **Component Reordering**: Users can reorder components vertically within the EditableBlock. _(Note: Dragging on the main canvas is not yet supported. Lack of main canvas dragging is acceptable in the editor at this stage.)_ _(Done at #4483)_
- [x] Allow delete  block children (_done at #4483)
- [x] Alt click to insert before _(done at https://github.com/webstudio-is/webstudio/pull/4479 )_
- [x] Meta Icons in Menu _(now BoxIcon is hardcoded)_ (#4487)
- [ ] ~Allow delete descendants of editable block children~ ????
- [ ] Make text more readable about deletion - toasts texts.
- [x] Change Icon for editable template https://www.figma.com/design/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?node-id=10054-1724&t=fUa78q94ZNOOlm8J-4 (#4486)
- [x] - Editable Block => Content Block #4489
- [x] - Plain tree, show only Content Blocks @TrySound 
- [x] - Alt converts `+` Icon to `Delete` icon. Inside menu we are writing `ALT`. Menu minWidth is not enough, max too. #4490
- [x] - Content Block without Templates is just wrapper which makes internal elements visible in navigation panel #4490
- [x] - Fix bug that after adding element it's not hoverable for like 500ms #4490 
- [x] - Fix bug that cursor TEXT is not applied to newly created elements in editable block #4490 
- [x] - Fix bug that something strange is happening with collapsed style when adding first template #4492
- [x] - Publish not working @istarkov #4495
- [x] - Menu height 24px @kof 
- [ ] - Default texts https://discord.com/channels/955905230107738152/1115982879651016814/1312810680834850907 #4498 
- [ ] -  Section ? <img width="260" alt="image" src="https://github.com/user-attachments/assets/6e6ac6da-42e5-40aa-8613-764447943ba8">

- [x] - When clicking "Content Block" in the navigator, nothing is scrolled into view. Only when clicking on the children. _It's an existing bug with scroll to display:contents_ #4519
- [x] - Content mode can publish. With can Publish checkbox #4530
- [x] - When a mode like "Content" is selected in share links, it's odd that clone and copy are checked and blue. _always was for every regime_ #4526
- [x] - When inserting a template instance, it should be selected automatically. Currently, the previously selected instance stays selected. #4519
- [x] - Disable project settings edit #4531
- [x] - Allow page clone #4531
- [x] - Change menu button on modern variant #4532
- [x] - Do not show  `Editable block you can edit` in preview #4533
- [x] - Toggle always between preview and current mode #4532

Roll out **WITH** public announcement.

## After Step 5. Explore drag-and-drop functionality on the main canvas.
- [ ] This step requires careful planning to avoid complexity that may lead to extensive development cycles. 
- [ ] Show rich text subcomponents settings & style panel during text edit i.e. link inside rich text

## Steps | Issues from @johnsicili 

- (just noting) Seems odd to have the right panel when the majority of the time it just consumes valuable space. I don't have ideas right now. Maybe in the future we'll add link and image editing in canvas and can do without right panel for clients
-  [x] - (known issue) Links are hard to edit when adding them inline
- [ ] - I don't love image dimension fields exposed because I often reduce the dimensions to better optimize. But if they replace the image then I guess it doesn't matter.
- [ ] - They can edit text content on XML. IDK if this is a problem.
- [ ] - ~Add info about publishing permissions to tooltip (e.g., Can publish with this permission)~
- [ ] - ~Disable Show toggle~

## Steps from @kof 
- [x] - Decide Content or Content Edit in share dialog?

**Comment by MilanBgd** [comment]
I think this feature gonna make the difference for our clients!

**Comment by ComputerTechs** [comment]
Can't wait for this feature!

**Comment by Zmove** [comment]
Definitely in the top 5 most important feature to me, near support of CSS grid, CSS variables and animation engine. That will allow us to definitely quit webflow for webstudio

**Comment by natanexus** [comment]
Honestly, this is the only feature i need to definetly use webstudio for my clients

**Comment by kof** [comment]
@Zmove special colors/borders etc are also not easy to understand after there are more than 3 and we already have use cases for 3.

Ghost elements in the navigator are essentially components. They don't necessarily represent DOM elements and I don't see them as something to avoid but rather the opposite. Yes they may need some more distinctive marking but generally they are not bad. They add indentation to help see what they contain which is better than memorizing  the meaning of many colors

**Comment by kof** [comment]
- [ ] decide how we mark properties that are available in content editing mode

**Comment by johnsicili** [comment]
- [ ] Add info about publishing permissions to tooltip (e.g., Can publish with this permission)

**Comment by johnsicili** [comment]
@istarkov added "Disable Show toggle" to Steps | Issues from @johnsicili

**Comment by riDuxd** [comment]
I know the team at Webstudio has been working hard on this feature, but I remember awhile back of this tool: https://github.com/GetmeUK/ContentTools

Why not just contribute and integrate it to Webstudio? To my limited understanding, the Content Mode is similar to Content Tools

**Comment by kof** [comment]
The way we did it will work with instances in webstudio, not just any wysiwyg, besides we already have wysiwyg but even there is not trivial to make it work with instances of components of any kind.

**Comment by riDuxd** [comment]
> The way we did it will work with instances in webstudio, its not just any wysiwyg, besides we already have wysiwyg but even there is not trivial to make it work with instances of components of any kind.

Got it, that makes sense, and your solution a lot more robust.
