### ISSUE TITLE
Modern font stacks

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#4121]
Custom font download results in a terrible slowdown of the website, where most people just want a certain type of the font, not a specific font and most OSs have a lot of similarly looking types that can be used.

This project has a great collection of such fonts with the corresponding fallbacks

https://github.com/system-fonts/modern-font-stacks

## Todo

- [x] Create a new section in fonts manager "Modern font stacks"
- [x] Add an (i) icon to explain that these wiill not install any downloadable fonts and link to the repo
- [x] Add the fonts with corresponding fallbacks
