### ISSUE TITLE
Overflow clip is the new overflow hidden

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#4203]
This article explains why https://www.bram.us/2024/02/14/scroll-driven-animations-you-want-overflow-clip-not-overflow-hidden/

## Todo
- [ ] replace the button for hidden with the button for clip
- [ ] ensure good tooltip text
- [ ] add an icon https://iconbuddy.com/search?q=crop
- [ ] ensure existing hidden value used by users is in advanced panel

**Comment by victorchrollo14** [comment]
hey @kof . will this be ok for the tooltip 
"Content that exceeds the container's boundaries is clipped  at the overflow clip edge and hidden without scrollbars"


This is the description given on mdn docs
![Image](https://github.com/user-attachments/assets/437ea38c-0c5d-477f-b725-1146f2c530d9)

**Comment by kof** [comment]
We already have this: "Clips the content with no scrollbars." ... not good?

**Comment by victorchrollo14** [comment]
what do you suggest then?. the clip property is similar to hidden with a few difference like we have the overflow-clip-margin property that let's you define how much content we can see beyond the clipped container, it also doesn't create scroll container as mentioned in the above blog. 

what about "Content that exceeds container's size is clipped and you can set the length of content visible beyond the clip using overflow-clip-margin" 

or shorten this a bit like 
"Content exceeding container size is clipped, with overflow-clip-margin controlling how much extra content shows."

**Comment by kof** [comment]
I am not sure what we are discussing, this issue is about adding this property to the visual panel. It already works via advanced panel. The description I mentioned is already used there

**Comment by victorchrollo14** [comment]
sorry about that, I didn't read the description for clip in advaned panel, I thought we were gonna add a new description for overflow: clip. 

I've replaced overflow hidden button with clip button, will raise a pr then.
