### ISSUE TITLE
Rich Text component

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#4595]
Content block is a better version of Rich Text, here is what's missing

- [x] slash command - lists the available instances inside templates, same as + button.  #4621
- [x] enter - creates a paragraph if paragrpah is available in templates
then `/` on empty paragraph if it's empty after adding a new block then we delete current block #4627

- [x] if there is no paragraph - newline
- [x] updated list of template instances according to wf richtext
- [ ] decide on the image block template to have a bunch of different  options for the layout
- [x] backspace on empty paragraph - deletes the paragraph and moves caret to the previous one #4627

- [x] UL/LI support #4633
- [x] Would be nice to auto exit after entering within an empty list item. #4641
- [x] Move `editablePlaceholderComponents` into meta https://github.com/webstudio-is/webstudio/blob/cd27371cc21445b0b841c9942047629ac652b99d/apps/builder/app/canvas/shared/styles.ts#L70
- [x] Placeholders #4644

Add:

- [x] - Select all text on new  #4627
