### ISSUE TITLE
Search for data and css variables

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#4608]
As a designer, I want to be able to find any token, data variable, css variable or instance by name.

## Todo

- [ ] virtualize the list to allow thouthands of items to get rendered
- [ ] when any of these items are found, enter - opens the right page and selects the right instance

## Later on

- [ ] type category:{term} to filter within one category
- [ ] when search matches category name, category gets selected, user hits enter, `category:{name} ` is inserted, now user can search within the category
- [ ] when category has more than X items, we show "show more" as the last item, enter/click on it does the sam as previous point - single-category search
- [ ] category itself could have a button for entering category search by mouse
